name: Fix PHP code style issues

on:
  push:
    paths:
      - '**.php'

permissions:
  contents: write

jobs:
  phplint:
    name: Laravel Pint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Laravel Pint
        uses: aglipanci/laravel-pint-action@latest
        with:
          configPath: "pint.json"

      # Optional: Automatically commit changes if you want to auto-fix and push
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fixing styling
